// Version 2 stores real Hz. Every patch resets the full signal chain.
const PATCH_DEFAULTS = {
    instrumentType: 'grand', instrumentTone: 0.7,
    __version: 2, synthMode: 'waveform', waveform: 'sawtooth', unison: 1, detune: 0,
    stereoSpread: 0.65, unisonBlend: 1, glideTime: 0, wavetablePosition: 0,
    fmToggle: false, fmAmount: 0, filterToggle: true, filterType: 'lowpass',
    filterCutoff: 5000, filterResonance: 0.7, filterEnvAmount: 0,
    attack: 0.008, decay: 0.3, sustain: 0.65, release: 0.25,
    lfoToggle: false, lfoRate: 0.3, lfoAmount: 30, noiseToggle: false, noiseAmount: 0,
    masterVolume: 0.72, masterReverb: 0.14, masterDelay: 0.1,
    delayDivision: '1/8D', delayFeedback: 0.32, chorusAmount: 0, driveAmount: 0,
    gateToggle: false, gateRate: '1/16', gateDepth: 0.8, gateSmooth: 0.018,
    sidechainToggle: false, sidechainAmount: 0.65, sidechainRelease: 0.22,
    kickToggle: false, kickLevel: 0.5, masterLowEQ: 0, masterMidEQ: 0, masterHighEQ: 0,
    arpToggle: false, arpClock: '16', arpPattern: 'up', arpSpeed: 1,
    __cthulhu: { enabled: false },
    __gate: { pattern: [1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0] }
};
const FACTORY_PATCHES = [
    { name: 'Trance Pluck', category: 'Pluck', color: 'lime', favorite: true,
      description: 'That late-night, hands-in-the-air feeling. A crisp attack with a luminous dotted echo.',
      character: 'Crisp · Wide · Dotted echo',
      settings: { unison: 3, detune: 12, filterCutoff: 601, filterResonance: 3.2,
        filterEnvAmount: 0.8, attack: 0.001, decay: 0.28, sustain: 0, release: 0.25,
        masterReverb: 0.28, masterDelay: 0.22, delayFeedback: 0.4 } },
    { name: 'Better Off Alone', category: 'Lead', color: 'peach', favorite: true,
      description: 'A familiar rush. Bright, direct sawtooth energy with a little space around the edges.',
      character: 'Classic · Bright · Immediate',
      settings: { unison: 7, detune: 0, filterType: 'highpass', filterCutoff: 23,
        filterResonance: 1, attack: 0.001, decay: 0.1, sustain: 1, release: 0.025,
        masterVolume: 0.58, masterReverb: 0.2, masterDelay: 0.08,
        masterLowEQ: -4, masterMidEQ: 1.5, masterHighEQ: 1 } },
    { name: 'Afterhours', category: 'Pluck', color: 'lime',
      description: 'Warm, woody transients that melt into the room. Leave a little space between the notes.',
      character: 'Warm · Intimate · Evolving',
      settings: { unison: 3, detune: 18, filterCutoff: 330, filterResonance: 1.5,
        filterEnvAmount: 0.5, attack: 0.004, decay: 0.42, sustain: 0.015, release: 0.4,
        masterReverb: 0.25, masterDelay: 0.19, chorusAmount: 0.1 } },
    { name: 'Starlight', category: 'Pluck', color: 'lime',
      description: 'A small spark with a long trail. Open the filter and let the echoes answer each other.',
      character: 'Sparkling · Airy · Rhythmic',
      settings: { unison: 4, detune: 9, filterCutoff: 1100, filterResonance: 1.6,
        filterEnvAmount: 0.55, attack: 0.002, decay: 0.22, sustain: 0, release: 0.28,
        masterReverb: 0.27, masterDelay: 0.3, delayFeedback: 0.44, masterHighEQ: -1.5 } },
    { name: 'Airwaves', category: 'Lead', color: 'peach',
      description: 'A wide, silky stack of saws. Built for melodies that deserve a bigger room.',
      character: 'Wide · Smooth · Euphoric',
      settings: { unison: 7, detune: 32, stereoSpread: 0.9, unisonBlend: 0.85,
        filterCutoff: 3400, filterResonance: 0.6, filterEnvAmount: 0.15,
        attack: 0.018, decay: 0.45, sustain: 0.72, release: 0.36,
        masterReverb: 0.25, masterDelay: 0.16, chorusAmount: 0.12, masterHighEQ: -1 } },
    { name: 'Soft Focus', category: 'Pad', color: 'lavender',
      description: 'Soft edges, wide horizons. Hold a chord and listen to the slow shimmer underneath.',
      character: 'Soft · Spacious · Analog',
      settings: { unison: 5, detune: 24, stereoSpread: 0.95, filterCutoff: 1450,
        filterEnvAmount: 0.16, attack: 0.7, decay: 1.2, sustain: 0.72, release: 1.8,
        chorusAmount: 0.28, masterReverb: 0.4, masterDelay: 0.12,
        lfoToggle: true, lfoRate: 0.2, lfoAmount: 100, masterLowEQ: -2 } },
    { name: 'Slow Bloom', category: 'Pad', color: 'lavender',
      description: 'A darker atmosphere that opens in its own time. Try a minor chord, then lift the cutoff.',
      character: 'Dark · Slow · Cinematic',
      settings: { unison: 6, detune: 19, filterCutoff: 520, filterEnvAmount: 0.3,
        attack: 1.25, decay: 2, sustain: 0.78, release: 2.6,
        chorusAmount: 0.22, masterReverb: 0.43, masterDelay: 0.15,
        lfoToggle: true, lfoRate: 0.1, lfoAmount: 70, masterLowEQ: -3 } },
    { name: 'Rubber', category: 'Bass', color: 'blue',
      description: 'Round, springy and right in the pocket. A short filter snap gives each note its bounce.',
      character: 'Round · Punchy · Dry',
      settings: { waveform: 'square', filterCutoff: 180, filterResonance: 2,
        filterEnvAmount: 0.32, attack: 0.004, decay: 0.19, sustain: 0.3, release: 0.09,
        masterReverb: 0, masterDelay: 0, driveAmount: 0.1, masterHighEQ: -3 } },
    { name: 'Undertow', category: 'Bass', color: 'blue',
      description: 'A low, moving foundation. Close detuning adds weight without swallowing the rest of the mix.',
      character: 'Deep · Rolling · Rounded',
      settings: { unison: 3, detune: 7, stereoSpread: 0.15, filterCutoff: 220,
        filterEnvAmount: 0.1, attack: 0.015, decay: 0.65, sustain: 0.7, release: 0.16,
        masterReverb: 0, masterDelay: 0, driveAmount: 0.12 } },
    { name: 'Acid Line', category: 'Bass', color: 'blue',
      description: 'A rounder acid groove with a little growl. A gentle filter snap keeps the bass underneath.',
      character: 'Liquid · Warm · Rolling',
      settings: { filterCutoff: 260, filterResonance: 3.4, filterEnvAmount: 0.3,
        attack: 0.004, decay: 0.3, sustain: 0.24, release: 0.14,
        glideTime: 0.035, driveAmount: 0.09, masterVolume: 0.67,
        masterReverb: 0.04, masterDelay: 0.09, delayDivision: '1/8', delayFeedback: 0.24,
        masterHighEQ: -2 } },
    { name: 'Glasshouse', category: 'Keys', color: 'sand',
      description: 'Clear, bell-like overtones over a soft fundamental. Small notes, big reflections.',
      character: 'Glassy · Delicate · FM',
      settings: { waveform: 'sine', fmToggle: true, fmAmount: 180,
        filterCutoff: 6500, attack: 0.002, decay: 1.1, sustain: 0, release: 1.2,
        masterReverb: 0.34, masterDelay: 0.2, delayFeedback: 0.37 } },
    { name: 'Velvet Keys', category: 'Keys', color: 'sand',
      description: 'Gentle, rounded keys with a soft chorus. An easy place to start a chord progression.',
      character: 'Mellow · Rounded · Lush',
      settings: { waveform: 'triangle', unison: 3, detune: 6, filterCutoff: 3200,
        attack: 0.01, decay: 0.9, sustain: 0.2, release: 0.7,
        fmToggle: true, fmAmount: 22, chorusAmount: 0.2,
        masterReverb: 0.25, masterDelay: 0.1 } },
    { name: 'Daydream', category: 'Pad', color: 'lavender',
      description: 'Soft Focus with the curtains drawn. A warm, low shimmer that leaves room for a melody.',
      character: 'Warm · Hazy · Unhurried',
      settings: { waveform: 'triangle', unison: 5, detune: 18, stereoSpread: 0.9,
        filterCutoff: 1800, filterEnvAmount: 0.1, attack: 0.85, decay: 1.7, sustain: 0.8,
        release: 2.2, fmToggle: true, fmAmount: 18, chorusAmount: 0.32,
        masterReverb: 0.38, masterDelay: 0.11, lfoToggle: true, lfoRate: 0.14, lfoAmount: 80 } },
    { name: 'Halo', category: 'Pad', color: 'lavender',
      description: 'A luminous saw cloud that slowly opens. Try wide chords and let the tail settle.',
      character: 'Luminous · Wide · Floating',
      settings: { unison: 7, detune: 28, stereoSpread: 1, unisonBlend: 0.8,
        filterCutoff: 2100, filterEnvAmount: 0.12, attack: 1.05, decay: 2.1, sustain: 0.68,
        release: 2.5, chorusAmount: 0.18, masterReverb: 0.44, masterDelay: 0.17,
        delayDivision: '1/4', delayFeedback: 0.3, masterLowEQ: -3, masterHighEQ: -2 } },
    { name: 'Blue Hour', category: 'Pad', color: 'lavender',
      description: 'Muted square waves, slowly breathing. A darker companion to Soft Focus.',
      character: 'Dark · Cushioned · Breathing',
      settings: { waveform: 'square', unison: 4, detune: 13, stereoSpread: 0.85,
        filterCutoff: 640, filterResonance: 0.5, filterEnvAmount: 0.13,
        attack: 0.55, decay: 1.5, sustain: 0.7, release: 1.7,
        chorusAmount: 0.3, masterReverb: 0.32, masterDelay: 0.08,
        lfoToggle: true, lfoRate: 0.12, lfoAmount: 110, masterLowEQ: -2 } },
    { name: 'Stillwater', category: 'Pad', color: 'lavender',
      description: 'A nearly weightless sine pad with a faint metallic glow. Best with a few notes held together.',
      character: 'Pure · Quiet · Reflective',
      settings: { waveform: 'sine', unison: 3, detune: 11, stereoSpread: 0.95,
        fmToggle: true, fmAmount: 65, filterCutoff: 2900, attack: 0.45,
        decay: 1.3, sustain: 0.75, release: 2.1, chorusAmount: 0.15,
        masterReverb: 0.43, masterDelay: 0.2, delayDivision: '1/4', delayFeedback: 0.38 } },
    { name: 'Porcelain', category: 'Keys', color: 'sand',
      description: 'A softer cousin of Glasshouse. Rounded bell tones with a short, intimate reflection.',
      character: 'Bell-like · Soft · Intimate',
      settings: { waveform: 'sine', fmToggle: true, fmAmount: 95,
        filterCutoff: 4200, attack: 0.005, decay: 1.25, sustain: 0.06, release: 0.8,
        chorusAmount: 0.08, masterReverb: 0.25, masterDelay: 0.12, delayFeedback: 0.25 } },
    { name: 'Prism', category: 'Keys', color: 'sand',
      description: 'Clear, bright tines that scatter into a stereo echo. Leave gaps for the reflections.',
      character: 'Crystal · Bright · Cascading',
      settings: { waveform: 'sine', fmToggle: true, fmAmount: 310,
        filterCutoff: 5200, attack: 0.003, decay: 0.7, sustain: 0, release: 1.1,
        masterReverb: 0.3, masterDelay: 0.27, delayFeedback: 0.4, masterHighEQ: -2 } },
    { name: 'Sunday Keys', category: 'Keys', color: 'sand',
      description: 'Velvet warmth with a little more body. Easy chords, soft attacks and a gently wavering tail.',
      character: 'Warm · Full · Relaxed',
      settings: { waveform: 'triangle', unison: 4, detune: 8, stereoSpread: 0.8,
        filterCutoff: 1800, filterEnvAmount: 0.06, attack: 0.018,
        decay: 1.3, sustain: 0.32, release: 1, fmToggle: true, fmAmount: 32,
        chorusAmount: 0.26, masterReverb: 0.22, masterDelay: 0.08 } },
    { name: 'Felt', category: 'Keys', color: 'sand',
      description: 'A close, muted key sound. A small hammer-like attack falls quickly into a warm fundamental.',
      character: 'Muted · Woody · Close',
      settings: { waveform: 'triangle', filterCutoff: 950, filterEnvAmount: 0.14,
        attack: 0.004, decay: 0.55, sustain: 0.08, release: 0.38,
        fmToggle: true, fmAmount: 14, masterReverb: 0.13, masterDelay: 0,
        chorusAmount: 0.06, masterHighEQ: -3 } },
    { name: 'Low Tide', category: 'Bass', color: 'blue',
      description: 'Undertow slowed to a gentle roll. A soft saw foundation with a little movement at the edge.',
      character: 'Deep · Soft · Steady',
      settings: { unison: 3, detune: 5, stereoSpread: 0.12,
        filterCutoff: 160, filterEnvAmount: 0.06, attack: 0.025,
        decay: 0.8, sustain: 0.8, release: 0.22, driveAmount: 0.07,
        masterReverb: 0, masterDelay: 0, masterHighEQ: -2 } },
    { name: 'Satin Sub', category: 'Bass', color: 'blue',
      description: 'A pure, even low end with just enough harmonic color to follow the notes. Try the lower octave.',
      character: 'Pure · Centered · Deep',
      settings: { waveform: 'sine', filterCutoff: 900, attack: 0.012,
        decay: 0.45, sustain: 0.85, release: 0.16, fmToggle: true, fmAmount: 12,
        stereoSpread: 0, driveAmount: 0.06, masterReverb: 0, masterDelay: 0 } },
    { name: 'Night Drive', category: 'Bass', color: 'blue',
      description: 'A compact, mellow pulse for moving basslines. A little bite up front, then a rounded sustain.',
      character: 'Pulsing · Compact · Warm',
      settings: { waveform: 'square', unison: 2, detune: 4, stereoSpread: 0.12,
        filterCutoff: 280, filterResonance: 1.2, filterEnvAmount: 0.16,
        attack: 0.006, decay: 0.24, sustain: 0.46, release: 0.13,
        glideTime: 0.02, driveAmount: 0.08, masterReverb: 0, masterDelay: 0 } },
    { name: 'Dewdrop', category: 'Pluck', color: 'lime',
      description: 'Tiny, rounded droplets with a glassy center. A lighter pluck for simple, repeating melodies.',
      character: 'Delicate · Round · Clear',
      settings: { waveform: 'sine', fmToggle: true, fmAmount: 110,
        filterCutoff: 3900, attack: 0.002, decay: 0.3, sustain: 0, release: 0.34,
        masterReverb: 0.28, masterDelay: 0.25, delayFeedback: 0.34 } },
    { name: 'Moonlit', category: 'Pluck', color: 'lime',
      description: 'A darker trance pluck with a soft, wide bloom. The echo does half the playing.',
      character: 'Dusky · Wide · Echoing',
      settings: { unison: 5, detune: 17, stereoSpread: 0.9,
        filterCutoff: 430, filterResonance: 1.4, filterEnvAmount: 0.4,
        attack: 0.004, decay: 0.45, sustain: 0.02, release: 0.55,
        chorusAmount: 0.12, masterReverb: 0.3, masterDelay: 0.27, delayFeedback: 0.4 } },
    { name: 'Paper Lantern', category: 'Pluck', color: 'lime',
      description: 'Hollow, woody notes with a little sparkle. Short phrases feel light and percussive.',
      character: 'Woody · Hollow · Playful',
      settings: { waveform: 'triangle', unison: 2, detune: 7,
        fmToggle: true, fmAmount: 48, filterCutoff: 2200, filterEnvAmount: 0.1,
        attack: 0.003, decay: 0.25, sustain: 0, release: 0.22,
        masterReverb: 0.17, masterDelay: 0.18, delayDivision: '1/8', delayFeedback: 0.28 } },
    { name: 'Silk', category: 'Lead', color: 'peach',
      description: 'A rounded, singing lead with a gentle glide. Keep the melody simple and let it linger.',
      character: 'Singing · Smooth · Warm',
      settings: { waveform: 'triangle', unison: 3, detune: 9, stereoSpread: 0.55,
        filterCutoff: 2600, filterEnvAmount: 0.06, fmToggle: true, fmAmount: 36,
        attack: 0.035, decay: 0.5, sustain: 0.78, release: 0.4, glideTime: 0.06,
        chorusAmount: 0.12, masterReverb: 0.23, masterDelay: 0.16 } },
    { name: 'Horizon', category: 'Lead', color: 'peach',
      description: 'Open, mellow saws with a broad stereo image. A softer lift for your main melody.',
      character: 'Open · Mellow · Expansive',
      settings: { unison: 5, detune: 20, stereoSpread: 0.85, filterCutoff: 1900,
        filterResonance: 0.6, filterEnvAmount: 0.15, attack: 0.024,
        decay: 0.6, sustain: 0.65, release: 0.45, chorusAmount: 0.18,
        masterReverb: 0.28, masterDelay: 0.19, masterHighEQ: -2 } },
    { name: 'Felt Piano', category: 'Piano', color: 'sand', newSound: true,
      description: 'A close, soft piano for small hours. Real grand-piano recordings, gently muted into felt-like warmth.',
      character: 'Recorded piano · Intimate · Soft',
      settings: { synthMode:'instrument', instrumentType:'felt', instrumentTone:.34,
        filterToggle:false, attack:.006, decay:3, sustain:1, release:.32,
        masterReverb:.25, masterDelay:.04, delayDivision:'1/4', masterHighEQ:-2 } },
    { name: 'Studio Grand', category: 'Piano', color: 'sand', newSound: true,
      description: 'A clear stereo grand with three recorded playing strengths. Try Soft and Firm touch, or use a MIDI keyboard.',
      character: 'Recorded piano · Natural · Expressive',
      settings: { synthMode:'instrument', instrumentType:'grand', instrumentTone:.86,
        filterToggle:false, attack:.002, decay:3, sustain:1, release:.24,
        masterReverb:.16, masterDelay:0, masterVolume:.76 } },
    { name: 'Dream Piano', category: 'Piano', color: 'lavender', newSound: true,
      description: 'Soft piano notes disappear into a slow, shimmering room. Use Sustain and leave space between chords.',
      character: 'Recorded piano · Shimmer · Spacious',
      settings: { synthMode:'instrument', instrumentType:'dream', instrumentTone:.52,
        filterToggle:false, attack:.012, decay:3, sustain:1, release:.9,
        chorusAmount:.13, masterReverb:.44, masterDelay:.23, delayDivision:'1/4', delayFeedback:.35 } },
    { name: 'Suitcase EP', category: 'Keys', color: 'sand', newSound: true,
      description: 'Round electric tines that growl a little when played firmly. Gentle chorus keeps the chords moving.',
      character: 'Electric piano · Tines · Warm',
      settings: { synthMode:'instrument', instrumentType:'tines', instrumentTone:.66,
        filterToggle:false, attack:.003, decay:1.1, sustain:1, release:.28,
        chorusAmount:.19, masterReverb:.19, masterDelay:.06, driveAmount:.025 } },
    { name: 'Amber Reed', category: 'Keys', color: 'peach', newSound: true,
      description: 'A woody electric piano with a soft, pulsing tremolo. Firm notes bring out its reed-like bite.',
      character: 'Electric piano · Reeds · Tremolo',
      settings: { synthMode:'instrument', instrumentType:'reed', instrumentTone:.68,
        filterToggle:false, attack:.004, decay:1.1, sustain:1, release:.2,
        driveAmount:.08, masterReverb:.13, masterDelay:0, masterLowEQ:-1 } },
    { name: 'Crystal EP', category: 'Keys', color: 'sand', newSound: true,
      description: 'A bright electric piano with a glassy strike and a rounded tail. Soft touch brings it back to a whisper.',
      character: 'Electric piano · FM · Glassy',
      settings: { synthMode:'instrument', instrumentType:'fmkeys', instrumentTone:.79,
        filterToggle:false, attack:.002, decay:1, sustain:1, release:.38,
        chorusAmount:.13, masterReverb:.28, masterDelay:.13, delayFeedback:.28 } },
    { name: 'Marimba', category: 'Mallet', color: 'peach', newSound: true,
      description: 'Rounded wooden bars with a quick, hollow knock. Play low notes for body and high notes for little sparks.',
      character: 'Wood · Mallets · Rounded',
      settings: { synthMode:'instrument', instrumentType:'marimba', instrumentTone:.64,
        filterToggle:false, attack:.002, decay:1.15, sustain:1, release:.28,
        masterReverb:.19, masterDelay:.08, delayDivision:'1/8', delayFeedback:.24 } },
    { name: 'Thumb Piano', category: 'Mallet', color: 'lime', newSound: true,
      description: 'Small metallic tines with a warm center. Simple patterns feel light, curious, and a little handmade.',
      character: 'Kalimba · Delicate · Metallic',
      settings: { synthMode:'instrument', instrumentType:'kalimba', instrumentTone:.74,
        filterToggle:false, attack:.002, decay:1.1, sustain:1, release:.4,
        masterReverb:.24, masterDelay:.16, delayFeedback:.3 } },
    { name: 'Moon Vibes', category: 'Mallet', color: 'blue', newSound: true,
      description: 'Mellow vibraphone bars with a gentle shimmer. Sustain lets the notes overlap into a floating harmony.',
      character: 'Vibraphone · Floating · Tremolo',
      settings: { synthMode:'instrument', instrumentType:'vibes', instrumentTone:.57,
        filterToggle:false, attack:.004, decay:1.2, sustain:1, release:.7,
        masterReverb:.31, masterDelay:.1, delayDivision:'1/4', delayFeedback:.24 } },
    { name: 'Sunday Organ', category: 'Keys', color: 'peach', newSound: true,
      description: 'Warm drawbar harmonics, a little percussion, and slow stereo movement. Hold a chord and let it settle.',
      character: 'Organ · Drawbars · Soulful',
      settings: { synthMode:'instrument', instrumentType:'organ', instrumentTone:.67,
        filterToggle:false, attack:.008, decay:.3, sustain:.9, release:.1,
        chorusAmount:.22, driveAmount:.035, masterReverb:.2, masterDelay:0, masterLowEQ:-2 } },
    { name: 'Chamber Strings', category: 'Pad', color: 'lavender', newSound: true,
      description: 'A small, warm synth-string ensemble with a slow bow and gentle vibrato. Open chords give it room to breathe.',
      character: 'Synth strings · Bowed · Warm',
      settings: { synthMode:'instrument', instrumentType:'strings', instrumentTone:.43,
        filterToggle:false, attack:.38, decay:1.2, sustain:.77, release:1.2,
        chorusAmount:.27, masterReverb:.34, masterDelay:.06, masterLowEQ:-2 } },
    { name: 'Cloud Choir', category: 'Pad', color: 'lavender', newSound: true,
      description: 'A soft, synthesized vowel cloud. Human-like harmonics open slowly behind your chords.',
      character: 'Synth choir · Vowels · Airy',
      settings: { synthMode:'instrument', instrumentType:'choir', instrumentTone:.78,
        filterToggle:false, attack:.65, decay:1.5, sustain:.78, release:1.8,
        chorusAmount:.24, masterReverb:.43, masterDelay:.12, masterLowEQ:-3 } }
].map((patch, index) => ({ ...patch, id: `factory:${patch.name}`, index,
    settings: { ...structuredClone(PATCH_DEFAULTS), ...patch.settings } }));
